"""initial

Revision ID: 001_initial
Revises: 
Create Date: 2026-05-11 16:31:42.065335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('MATCHING', 'LOCKED', 'VERIFYING', 'LOADING', 'IN_TRANSIT', 'ARRIVED_URBAN', 'DELIVERED', 'FAILED', name='shipmentstatus'), nullable=False),
    sa.Column('failure_category', sa.Enum('TIMEOUT', 'INSUFFICIENT_SUPPLY', 'QUALITY_REJECTION', 'LOGISTICS_BREAKDOWN', 'OPERATIONAL_INCONSISTENCY', 'FRAUD', name='shipmentfailurecategory'), nullable=True),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('crop', sa.String(), nullable=False),
    sa.Column('target_quantity_bags', sa.Integer(), nullable=False),
    sa.Column('actual_quantity_bags', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matching_timeout', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loading_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_urban_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_region'), 'shipments', ['region'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('BUYER', 'FARMER', 'AGENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('ORDER_CONFIRMED', 'GRACE_PERIOD_ENDING', 'SHIPMENT_FULL', 'PICKUP_SCHEDULED', 'LORRY_DISPATCHED', 'LORRY_ARRIVED', 'DELIVERY_COMPLETED', 'PAYMENT_CONFIRMED', 'DISPUTE', 'ADMIN_ALERT', name='notificationtype'), nullable=False),
    sa.Column('channel', sa.Enum('PUSH', 'SMS', name='notificationchannel'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESERVED', 'PARTIALLY_FULFILLED', 'FULFILLED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('quantity_bags', sa.Integer(), nullable=False),
    sa.Column('price_per_bag', sa.Integer(), nullable=False),
    sa.Column('delivery_location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_buyer_id'), 'orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_orders_shipment_id'), 'orders', ['shipment_id'], unique=False)
    op.create_table('verification_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'ADJUSTED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('claimed_quantity_bags', sa.Integer(), nullable=False),
    sa.Column('actual_quantity_bags', sa.Integer(), nullable=True),
    sa.Column('quality_notes', sa.String(), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('client_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_verification_reports_shipment_id'), 'verification_reports', ['shipment_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('available_balance_cents', sa.Integer(), nullable=False),
    sa.Column('locked_balance_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.Enum('DEPOSIT', 'RESERVATION', 'RESERVATION_REVERSAL', 'PAYOUT', 'REFUND', 'PLATFORM_FEE', 'TRANSPORT_FEE', name='ledgerentrytype'), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_wallet_id'), 'ledger_entries', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_wallet_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_verification_reports_shipment_id'), table_name='verification_reports')
    op.drop_table('verification_reports')
    op.drop_index(op.f('ix_orders_shipment_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_region'), table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###