"""phase9_harvest_location_shipment_verification

Revision ID: 11cd7d578017
Revises: 47a3d5f7f21a
Create Date: 2026-05-15 09:51:53.661353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11cd7d578017'
down_revision: Union[str, None] = '47a3d5f7f21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvests', sa.Column('shipment_id', sa.UUID(), nullable=True))
    op.add_column('harvests', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('harvests', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_index(op.f('ix_harvests_shipment_id'), 'harvests', ['shipment_id'], unique=False)
    op.create_foreign_key(None, 'harvests', 'shipments', ['shipment_id'], ['id'])
    op.add_column('verification_reports', sa.Column('harvest_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_verification_reports_harvest_id'), 'verification_reports', ['harvest_id'], unique=False)
    op.create_foreign_key(None, 'verification_reports', 'harvests', ['harvest_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_reports', type_='foreignkey')
    op.drop_index(op.f('ix_verification_reports_harvest_id'), table_name='verification_reports')
    op.drop_column('verification_reports', 'harvest_id')
    op.drop_constraint(None, 'harvests', type_='foreignkey')
    op.drop_index(op.f('ix_harvests_shipment_id'), table_name='harvests')
    op.drop_column('harvests', 'longitude')
    op.drop_column('harvests', 'latitude')
    op.drop_column('harvests', 'shipment_id')
    # ### end Alembic commands ###