"""add_pricing_configs

Revision ID: 3d0c097a00b7
Revises: 62380f69fc54
Create Date: 2026-05-15 10:23:16.284064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0c097a00b7'
down_revision: Union[str, None] = '62380f69fc54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('crop', sa.String(), nullable=True),
    sa.Column('base_market_price_cents', sa.Integer(), nullable=False),
    sa.Column('platform_fee_cents', sa.Integer(), nullable=False),
    sa.Column('transport_fee_cents', sa.Integer(), nullable=False),
    sa.Column('buyer_discount_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region', 'crop', name='uq_pricing_region_crop')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_configs')
    # ### end Alembic commands ###