"""make_firebase_uid_nullable

Revision ID: 478e5542e82b
Revises: 11cd7d578017
Create Date: 2026-05-15 10:13:26.358524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478e5542e82b'
down_revision: Union[str, None] = '11cd7d578017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###