"""add_feedbacks_table

Revision ID: 4e165ff6f027
Revises: 984a31faca54
Create Date: 2026-05-16 07:12:55.780868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e165ff6f027'
down_revision: Union[str, None] = '984a31faca54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('verification_report_id', sa.UUID(), nullable=True),
    sa.Column('feedback_type', sa.Enum('BUYER_TO_FARMER', 'AGENT_TO_FARMER', name='feedbacktype'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verification_report_id'], ['verification_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('ratings', 'overall_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('5.0'))
    op.alter_column('ratings', 'total_transactions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ratings', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('ratings_user_id_key', 'ratings', type_='unique')
    op.create_index(op.f('ix_ratings_user_id'), 'ratings', ['user_id'], unique=True)
    op.alter_column('users', 'approval_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'approval_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_index(op.f('ix_ratings_user_id'), table_name='ratings')
    op.create_unique_constraint('ratings_user_id_key', 'ratings', ['user_id'])
    op.alter_column('ratings', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ratings', 'total_transactions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ratings', 'overall_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('5.0'))
    op.drop_table('feedbacks')
    # ### end Alembic commands ###