"""add_agent_gps_to_users

Revision ID: 6073dca0ea14
Revises: 4e165ff6f027
Create Date: 2026-05-16 07:37:27.945479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6073dca0ea14'
down_revision: Union[str, None] = '4e165ff6f027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_role', 'ratings', type_='unique')
    op.add_column('users', sa.Column('gps_latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('gps_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gps_longitude')
    op.drop_column('users', 'gps_latitude')
    op.create_unique_constraint('unique_user_role', 'ratings', ['user_id', 'role'])
    # ### end Alembic commands ###