"""add_actual_quantity_to_harvests

Revision ID: 62380f69fc54
Revises: 478e5542e82b
Create Date: 2026-05-15 10:19:05.923853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62380f69fc54'
down_revision: Union[str, None] = '478e5542e82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvests', sa.Column('actual_quantity_bags', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('harvests', 'actual_quantity_bags')
    # ### end Alembic commands ###