"""add_payment_mode_and_payout_status

Revision ID: 683a66f12d64
Revises: 6073dca0ea14
Create Date: 2026-05-16 08:10:40.980048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683a66f12d64'
down_revision: Union[str, None] = '6073dca0ea14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Column('payout_status', sa.VARCHAR(), nullable=False, server_default='PENDING_PAYOUT')
    sa.Column('payment_mode', sa.VARCHAR(), nullable=False, server_default='AUTO_ESCROW')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_mode')
    op.drop_column('harvests', 'payout_status')
    # ### end Alembic commands ###