"""add_profile_picture_and_approval

Revision ID: 984a31faca54
Revises: 3bdaff84bf79
Create Date: 2026-05-16 06:36:50.814813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '984a31faca54'
down_revision: Union[str, None] = '3bdaff84bf79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'overall_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('5.0'))
    op.alter_column('ratings', 'total_transactions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ratings', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('ratings_user_id_key', 'ratings', type_='unique')
    op.create_index(op.f('ix_ratings_user_id'), 'ratings', ['user_id'], unique=True)
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'approval_status')
    op.drop_column('users', 'profile_picture_url')
    op.drop_index(op.f('ix_ratings_user_id'), table_name='ratings')
    op.create_unique_constraint('ratings_user_id_key', 'ratings', ['user_id'])
    op.alter_column('ratings', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ratings', 'total_transactions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ratings', 'overall_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('5.0'))
    # ### end Alembic commands ###