"""add_device_tokens

Revision ID: a62709bfeef2
Revises: d31e63fc1bcd
Create Date: 2026-05-15 10:59:12.802143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a62709bfeef2'
down_revision: Union[str, None] = 'd31e63fc1bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE notifications ALTER COLUMN data TYPE JSONB USING data::jsonb')
    op.alter_column('notifications', 'data',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE notifications ALTER COLUMN data TYPE VARCHAR')
    op.alter_column('notifications', 'data',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='data::jsonb')
    # ### end Alembic commands ###